import type { NextPage } from 'next'
import Head from 'next/head'
import MainApp from './MainApp'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Quiz App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon.ico" />
      </Head>

      <main className={styles.main}>
        <MainApp />
      </main>
    </div>
  )
}

export default Home
